lib/rsvp_web/router.ex
defmodule RsvpWeb.Router do
  use RsvpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RsvpWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/events", EventController
    resources "/event_responses", EventResponseController

    get "/events/:id/responses", EventController, :responses
  end

  # Other scopes may use custom stacks.
  # scope "/api", RsvpWeb do
  #   pipe_through :api
  # end
end

lib/rsvp/events.ex
defmodule Rsvp.Events do
  @moduledoc """
  The Events context.
  """

  import Ecto.Query, warn: false
  alias Rsvp.Repo

  alias Rsvp.Events.Event

  @doc """
  Returns the list of events.

  ## Examples

      iex> list_events()
      [%Event{}, ...]

  """
  def list_events do
    Repo.all(Event)
  end

  @doc """
  Gets a single event.

  Raises `Ecto.NoResultsError` if the Event does not exist.

  ## Examples

      iex> get_event!(123)
      %Event{}

      iex> get_event!(456)
      ** (Ecto.NoResultsError)

  """
  def get_event!(id), do: Repo.get!(Event, id)

  @doc """
  Creates a event.

  ## Examples

      iex> create_event(%{field: value})
      {:ok, %Event{}}

      iex> create_event(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_event(attrs \\ %{}) do
    %Event{}
    |> Event.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a event.

  ## Examples

      iex> update_event(event, %{field: new_value})
      {:ok, %Event{}}

      iex> update_event(event, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_event(%Event{} = event, attrs) do
    event
    |> Event.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Event.

  ## Examples

      iex> delete_event(event)
      {:ok, %Event{}}

      iex> delete_event(event)
      {:error, %Ecto.Changeset{}}

  """
  def delete_event(%Event{} = event) do
    Repo.delete(event)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking event changes.

  ## Examples

      iex> change_event(event)
      %Ecto.Changeset{source: %Event{}}

  """
  def change_event(%Event{} = event) do
    Event.changeset(event, %{})
  end
end

lib/rsvp/events/event.ex
defmodule Rsvp.Events.Event do
  use Ecto.Schema
  import Ecto.Changeset

  schema "events" do
    field :date, :naive_datetime
    field :title, :string

    has_many :event_responses, Rsvp.EventResponses.EventResponse

    timestamps()
  end

  @doc false
  def changeset(event, attrs) do
    event
    |> cast(attrs, [:title, :date])
    |> validate_required([:title, :date])
  end
end

lib/rsvp_web/controllers/event_controller.ex
defmodule RsvpWeb.EventController do
  use RsvpWeb, :controller

  alias Rsvp.Events
  alias Rsvp.Events.Event

  alias Rsvp.EventResponses
  alias Rsvp.EventResponses.EventResponse

  def index(conn, _params) do
    events = Events.list_events()
    render(conn, "index.html", events: events)
  end

  def new(conn, _params) do
    changeset = Events.change_event(%Event{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"event" => event_params}) do
    case Events.create_event(event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event created successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    event = Events.get_event!(id)
    changeset = EventResponses.change_event_response(%EventResponse{})
    render(conn, "show.html", event: event, changeset: changeset)
  end

  def responses(conn, %{"id" => id}) do
    event = Events.get_event!(id)
    event_responses = EventResponses.list_event_responses_for_event(id)
    render(conn, "responses.html", event: event, event_responses: event_responses)
  end

  def edit(conn, %{"id" => id}) do
    event = Events.get_event!(id)
    changeset = Events.change_event(event)
    render(conn, "edit.html", event: event, changeset: changeset)
  end

  def update(conn, %{"id" => id, "event" => event_params}) do
    event = Events.get_event!(id)

    case Events.update_event(event, event_params) do
      {:ok, event} ->
        conn
        |> put_flash(:info, "Event updated successfully.")
        |> redirect(to: Routes.event_path(conn, :show, event))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", event: event, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    event = Events.get_event!(id)
    {:ok, _event} = Events.delete_event(event)

    conn
    |> put_flash(:info, "Event deleted successfully.")
    |> redirect(to: Routes.event_path(conn, :index))
  end
end

lib/rsvp_web/views/event_view.ex
defmodule RsvpWeb.EventView do
  use RsvpWeb, :view
end

lib/rsvp_web/templates/event/edit.html.eex
<h1>Edit Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :update, @event)) %>

<%#= render RsvpWeb.EventResponseView, "form.html", Map.put(assigns, :action, Routes.event_response_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.event_path(@conn, :index) %></span>

lib/rsvp_web/templates/event/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :date %>
  <%= datetime_select f, :date %>
  <%= error_tag f, :date %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/rsvp_web/templates/event/index.html.eex
<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for event <- @events do %>
    <tr>
      <td><%= event.title %></td>
      <td><%= event.date %></td>

      <td>
        <span><%= link "Show", to: Routes.event_path(@conn, :show, event) %></span>
        <span><%= link "Edit", to: Routes.event_path(@conn, :edit, event) %></span>
        <span><%= link "Delete", to: Routes.event_path(@conn, :delete, event), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Event", to: Routes.event_path(@conn, :new) %></span>

lib/rsvp_web/templates/event/new.html.eex
<h1>New Event</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.event_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.event_path(@conn, :index) %></span>

lib/rsvp_web/templates/event/responses.html.eex
<h1>Event Responses</h1>

<h2>
  Event: <%= link @event.title, to: Routes.event_path(@conn, :show, @event) %>
</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Going</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for event_response <- @event_responses do %>
    <tr>
      <td><%= event_response.name %></td>
      <td><%= event_response.email %></td>
      <td><%= event_response.going %></td>

      <td>
        <span><%= link "Show", to: Routes.event_response_path(@conn, :show, event_response) %></span>
        <span><%= link "Edit", to: Routes.event_response_path(@conn, :edit, event_response) %></span>
        <span><%= link "Delete", to: Routes.event_response_path(@conn, :delete, event_response), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/rsvp_web/templates/event/show.html.eex
<h1>Show Event</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @event.title %>
  </li>

  <li>
    <strong>Date:</strong>
    <%= @event.date %>
  </li>

</ul>

<%= render RsvpWeb.EventResponseView, "form.html", Map.put(assigns, :action, Routes.event_response_path(@conn, :create)) %>

<span><%= link "Edit", to: Routes.event_path(@conn, :edit, @event) %></span>
<span><%= link "Back", to: Routes.event_path(@conn, :index) %></span>